# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Container App - dev-insights-samunnati

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      # - name: Build Docker image
      #   run: |
      #     docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/bi_insights:latest.

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER_UAT }}
          username: ${{ secrets.ACR_USERNAME_UAT }}
          password: ${{ secrets.ACR_PASSWORD_UAT }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{secrets.ACR_LOGIN_SERVER_UAT}}/bi_insights:latest

      # - name: Push Docker image to ACR
      #   run: |
      #     docker push ${{ secrets.ACR_LOGIN_SERVER }}/bi_insights:latest

      # - name: Azure Login
      #   uses: azure/login@v2
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Deploy to Azure Container App
      #   uses: azure/container-apps-deploy-action@v1
      #   with:
      #     app-name: "dev-insights-samunnati"
      #     resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
      #     image: ${{ secrets.ACR_LOGIN_SERVER }}/dev-insights-samunnati:${{ github.sha }}
      #     container-app-env: ${{ secrets.AZURE_CONTAINERAPPS_ENVIRONMENT }}

      - name: Deploy latest image to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "dev-insights-samunnati"
          slot-name: "production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_65FE2AE65A734E7DB169609AA1222DEF }}
